name: family_game_score
description: "A new Flutter project."

publish_to: 'none' 

version: 1.5.0+19

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_serializable: ^6.6.0
  sqflite: ^2.4.1
  firebase_core: ^3.9.0
  firebase_crashlytics: ^4.2.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  permission_handler: ^11.3.1
  table_calendar: ^3.1.3
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.2
  flutter_screenutil: ^5.9.3
  go_router: ^14.6.2


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon_android.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon_android.png"
  min_sdk_android: 21

  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

  flutter_lints: ^3.0.0


flutter:
  generate: true 

  uses-material-design: true

  fonts:
    - family: MPLUSRounded1c-Regular
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Regular.ttf
    - family: MPLUSRounded1c-Medium
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Medium.ttf